version: "3.9"

services:
  node_app:
    container_name: backend
    build: .
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - REDIS_URI=${REDIS_URI}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    restart: always
    links:
      - redis

  postgres:
    build: ./src/user/infrastructure/postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  client_app:
   container_name: frontend
   build: ./client
   ports:
     - "3000:3000"
   depends_on:
     - node_app
